version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
