name: Fetch and Push Data

on:
  push:
    # paths:
      # - 'output/reports/visuals/dynamic/**'

jobs:
  fetch-and-push:
    runs-on: macos-latest

    steps:
      # - name: Set up environment variables
      #   run: |
      #     python3.11 -m pip install python-dotenv
      #     dotenv run env -f .env

      - name: Checkout toxins-in-skincare repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name ${{ maha.kanakala }}
          git config --global user.email ${{ maha.kanakala@gmail.com }}

      - name: Fetch data from toxins-in-skincare repository and create data directory
        run: |
          mkdir -p ~/data
          cp -R output/reports/visuals/dynamic ~/data

      - name: Clone toxins-web repository
        run: |
          git clone https://github.com/mahakanakala/toxins-web.git
          cd toxins-web
          git config user.name ${{ env.USER_NAME }}
          git config user.email ${{ env.USER_EMAIL }}

          echo "${{ secrets.GITHUB_TOKEN }}" | git credential-osxkeychain erase
          echo "${{ secrets.GITHUB_TOKEN }}" | git credential-osxkeychain store

      - name: Copy data to toxins-web repository
        run: |
          mkdir -p ~/toxins-web/output/reports/visuals/dynamic
          cp -R ~/data/dynamic ~/toxins-web/public/visualization/dynamic

      - name: Commit and push changes to toxins-web repository
        run: |
          cd ~/toxins-web
          git add .
          git commit -m 'Update dynamic visualizations'
          git push origin HEAD

      - name: Clean up temporary data directory
        run: rm -rf ~/data
